INSERT INTO ADDRESS(ID, STREET, CITY, HOUSE_NUMBER, HOUSE_NUMBER_ADD_ON)
VALUES(1, 'ILICA', 'ZAGREB', 1, 'A');

INSERT INTO ADDRESS(ID, STREET, CITY, HOUSE_NUMBER, HOUSE_NUMBER_ADD_ON)
VALUES(2, 'SAMOBORSKA', 'ZAGREB', 100, 'C');

