INSERT INTO ADDRESS(ID, STREET, CITY, HOUSE_NUMBER, HOUSE_NUMBER_ADD_ON)
VALUES(1, 'ILICA', 'ZAGREB', 1, 'A');

INSERT INTO ADDRESS(ID, STREET, CITY, HOUSE_NUMBER, HOUSE_NUMBER_ADD_ON)
VALUES(2, 'SAMOBORSKA', 'ZAGREB', 100, 'C');

INSERT INTO ADDRESS(ID, STREET, CITY, HOUSE_NUMBER, HOUSE_NUMBER_ADD_ON)
VALUES(3, 'ZAGREBACKA', 'ZAGREB', 180, 'C');

INSERT INTO ADDRESS(ID, STREET, CITY, HOUSE_NUMBER, HOUSE_NUMBER_ADD_ON)
VALUES(4, 'SLAVONSKA', 'ZAGREB', 110, 'A');

INSERT INTO REAL_ESTATE(ID, ADDRESS_ID, AREA)
VALUES(1, 1, 50);

INSERT INTO REAL_ESTATE(ID, ADDRESS_ID, AREA)
VALUES(2, 2, 60);

INSERT INTO REAL_ESTATE(ID, ADDRESS_ID, AREA)
VALUES(3, 3, 100);

INSERT INTO REAL_ESTATE(ID, ADDRESS_ID, AREA)
VALUES(4, 4, 120);

INSERT INTO APARTMENT(ID, FLOOR_NUMBER)
VALUES(1, 0);

INSERT INTO APARTMENT(ID, FLOOR_NUMBER)
VALUES(2, 1);

INSERT INTO HOUSE(ID, YARD_AREA, NUMBER_OF_FLOORS)
VALUES(3, 1000, 3);

INSERT INTO HOUSE(ID, YARD_AREA, NUMBER_OF_FLOORS)
VALUES(4, 100, 2);