INSERT INTO ADDRESS(ID, STREET, CITY, HOUSE_NUMBER, HOUSE_NUMBER_ADD_ON)
VALUES(1, 'ILICA', 'ZAGREB', 1, 'A');

INSERT INTO ADDRESS(ID, STREET, CITY, HOUSE_NUMBER, HOUSE_NUMBER_ADD_ON)
VALUES(2, 'SAMOBORSKA', 'ZAGREB', 100, 'C');

INSERT INTO APARTMENT(ID, FLOOR_NUMBER, ADDRESS_ID)
VALUES(1, 0, 1);

INSERT INTO APARTMENT(ID, FLOOR_NUMBER, ADDRESS_ID)
VALUES(2, 1, 2);